name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Exemplo simples de CI para projeto estático
      - name: Verificar arquivos
        run: |
          if [ ! -f index.html ]; then
            echo "Erro: index.html não encontrado!"
            exit 1
          fi
          echo "Todos os arquivos principais existem."
